package rules.civil.decision

import com.laa.model.civil.CivilDecisionReport;
import java.math.BigDecimal;

dialect "java" 



rule "Gross income limit check"
	when
		
		$decision : CivilDecisionReport( grossIncome!=null && grossIncome.compareTo(new BigDecimal("2657.00")) < 0)
		
	then
				System.out.println(drools.getRule().getName());
		$decision.setWithinGrossIncomeLimit(true);
		update($decision);
		
end

rule "Disposable income limit check"
	when
		
		$decision : CivilDecisionReport( disposableIncome != null  && disposableIncome.compareTo(new BigDecimal("733.00")) < 0)
		
	then
				System.out.println(drools.getRule().getName());
		$decision.setWithinDisposableIncomeLimit(true);
		update($decision);
		
end

rule "Capital assets under limit "
	when
		
		$decision : CivilDecisionReport(capitalAssessment !=null && capitalAssessment.compareTo(new BigDecimal("3000.00")) < 0)
		
	then
				System.out.println(drools.getRule().getName());
		$decision.setWithinCapitalAssetsLimit(true);
		update($decision);
end

rule "Capital assets over limit "
	when
		
		$decision : CivilDecisionReport(capitalAssessment !=null && capitalAssessment.compareTo(new BigDecimal("3000.00")) > 0)
		
	then
				System.out.println(drools.getRule().getName());
		$decision.setWithinCapitalAssetsLimit(false);
		update($decision);
end



rule "Verify if means assesment is passed"
	when
		$decision: CivilDecisionReport(withinGrossIncomeLimit == true, withinDisposableIncomeLimit == true,  withinCapitalAssetsLimit == true )
	then
				System.out.println(drools.getRule().getName());
		$decision.setMeansPassed(true);

end

rule "means assessment after failing capital assessment without domestic violence waiver"
	when
		$decision: CivilDecisionReport(domesticViolenceWaiver == false, withinGrossIncomeLimit == true, withinDisposableIncomeLimit == true,  withinCapitalAssetsLimit == false )
	then
			System.out.println(drools.getRule().getName());
		$decision.setMeansPassed(false);

end


rule "means assessment after failing capital assessment with domestic violence waiver"
	when
		$decision: CivilDecisionReport(domesticViolenceWaiver == true, withinGrossIncomeLimit == true, withinDisposableIncomeLimit == true,  withinCapitalAssetsLimit == false )
	then
			System.out.println(drools.getRule().getName());
		$decision.setMeansPassed(true);

end




















